# Introduction

This repository contains the Quarto source files of the practical exercises for the *Introduction to Social Attitudes Surveys* UKDS Data Skills Module.


A key aim of the BSA is to track the views and opinions of the public on national issues over time. The BSA questionnaire has core questions that are repeated in most years. 
These cover different topics such as politics, welfare, poverty,  health, education, equalities, and employment.
In addition, the interview questionnaire consists of various background and demographic questions. 
The rest of the questionnaire  includes a series of non-core questions (modules) on a number of social, political, economic and moral topics, which are included in the survey  less frequently.

Direct links to the HTML pages of the exercises on GitHub Pages:
  
- R version:
  
    - <a href="https://ukdataserviceopen.github.io/Introduction_to_the_BSA/Population estimates using the BSAS with R.html" target="_blank" rel="noopener noreferrer" >Basic population estimates with BSA data using R </a>
    - <a href="https://ukdataserviceopen.github.io/Introduction_to_the_BSA/infer_w_survey_design_usingR.html" target="_blank" rel="noopener noreferrer" >Survey design informed inference with BSA data using R</a>
  
- SPSS version:
  
  - <a href="https://ukdataserviceopen.github.io/Introduction_to_the_BSA/Pop_estimates_using_the_BSAS_and_SPSS.html" target="_blank" rel="noopener noreferrer" >Basic population estimates with BSA data using SPSS </a>
  - <a href="https://ukdataserviceopen.github.io/Introduction_to_the_BSA/infer_w_survey_design_usingSPSS.html" target="_blank" rel="noopener noreferrer" > Survey design informed inference with BSA data using SPSS </a>
  