<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.554">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="UK Data Service">

<title>Basic population estimates with British Social Attitudes Survey data using R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Population estimates using the BSAS with R_files/libs/clipboard/clipboard.min.js"></script>
<script src="Population estimates using the BSAS with R_files/libs/quarto-html/quarto.js"></script>
<script src="Population estimates using the BSAS with R_files/libs/quarto-html/popper.min.js"></script>
<script src="Population estimates using the BSAS with R_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Population estimates using the BSAS with R_files/libs/quarto-html/anchor.min.js"></script>
<link href="Population estimates using the BSAS with R_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Population estimates using the BSAS with R_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Population estimates using the BSAS with R_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Population estimates using the BSAS with R_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Population estimates using the BSAS with R_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: #742082;
      }

      .quarto-title-block .quarto-title-banner {
        color: #742082;
background: white;
      }
</style>


<link rel="stylesheet" href="ukds.css">
</head>

<body>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Basic population estimates with British Social Attitudes Survey data using R</h1>
                      </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>UK Data Service </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">June 2024</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#getting-started" id="toc-getting-started" class="nav-link active" data-scroll-target="#getting-started">Getting started</a></li>
  <li><a href="#explore-the-dataset" id="toc-explore-the-dataset" class="nav-link" data-scroll-target="#explore-the-dataset">1. Explore the dataset</a></li>
  <li><a href="#missing-values" id="toc-missing-values" class="nav-link" data-scroll-target="#missing-values">2. Missing values</a></li>
  <li><a href="#compare-unweighted-and-weighted-proportions" id="toc-compare-unweighted-and-weighted-proportions" class="nav-link" data-scroll-target="#compare-unweighted-and-weighted-proportions">3. Compare unweighted and weighted proportions</a></li>
  <li><a href="#confidence-intervals" id="toc-confidence-intervals" class="nav-link" data-scroll-target="#confidence-intervals">4. Confidence intervals</a></li>
  <li><a href="#answers" id="toc-answers" class="nav-link" data-scroll-target="#answers">Answers</a></li>
  <li><a href="#appendix-recoding-nonresponses-as-system-missing-na" id="toc-appendix-recoding-nonresponses-as-system-missing-na" class="nav-link" data-scroll-target="#appendix-recoding-nonresponses-as-system-missing-na">Appendix: recoding nonresponses as system missing (NA)</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">





<p>This exercise is part of the <a href="https://trainingmodules.ukdataservice.ac.uk/attitudes/#/" target="_blank" rel="noopener">‘Introduction to the British Social Attitudes Survey (BSA)’</a> online module. In the exercise, we examine data from the 2020 British Social Attitudes survey to find out:</p>
<ul>
<li><p>what proportion of respondents said they voted remain in the EU Referendum?</p></li>
<li><p>whether people think the government should raise taxes and spend more or reduce tax and cut social expenditures?</p></li>
<li><p>how much people think they’ll get from the State pension?</p></li>
</ul>
<p>Answers to the questions asked throughout the exercise can be found at the end of the page.</p>
<section id="getting-started" class="level3">
<h3 class="anchored" data-anchor-id="getting-started">Getting started</h3>
<p>Data can be downloaded from the <a href="https://beta.ukdataservice.ac.uk/datacatalogue/studies/study?id=9005" target="_blank" rel="noopener">UK Data Service website</a> following <a href="https://ukdataservice.ac.uk/help/registration/registration-login-faqs/" target="_blank" rel="noopener">registration</a>. Download the compressed folder, unzip and save it somewhere accessible on your computer.</p>
<p>The examples below assume that the dataset has been saved in a new folder named <em>UKDS</em> on your Desktop (Windows computers). The path would typically be <code>C:\Users\YOUR_USER_NAME\Desktop\UKDS</code>. Feel free to change it to the location that best suits your needs.</p>
<p>We begin by loading the R packages needed for the exercise and set the working directory.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr) <span class="do">### Data manipulation functions</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven) <span class="do">### Functions for importing data from </span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>               <span class="do">### commercial packages</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Hmisc) <span class="do">### Extra statistical functions</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="do">### Setting up the working directory</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="do">### Please adjust the setwd() command  below   </span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="do">### to match the location of the data on your computer </span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:\Users\Your_Username_here</span><span class="sc">\"</span><span class="st">)</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="st">getwd()</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>[1] C:\Users\Your_Username_here\</code></p>
<p>We then open the BSA dataset in SPSS format. Stata or tab-delimited format can also be used.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>bsa20<span class="ot">&lt;-</span><span class="fu">read_spss</span>(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>       <span class="st">'UKDA-9005-spss/spss/spss25/bsa2020_archive.sav'</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>       ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="explore-the-dataset" class="level3">
<h3 class="anchored" data-anchor-id="explore-the-dataset">1. Explore the dataset</h3>
<p>Start by getting an overall feel for the data. Either inspect variables and cases in the data editor or use the code below to produce a summary of all the variables in the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Gives the number of rows (observations) </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="do">### and columns (variables)</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(bsa20) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3964  210</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a> <span class="do">### List variable names in their actual </span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a> <span class="do">### order in the dataset</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(bsa20)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] "serial"       "QnrVersion"   "RespSx2cat"   "RespAgeE"     "MarStat6"    
  [6] "REconFW01"    "REconFW02"    "REconFW03"    "REconFW04"    "REconFW05"   
 [11] "REconFW06"    "REconFW07"    "REconFW08"    "REconFW09"    "REconFW10"   
 [16] "REconFW11"    "EMPSTAT"      "Employ"       "Superv"       "EmpOCC"      
 [21] "TenureE"      "SupParty"     "ClosePty"     "PARTYFW"      "Idstrng"     
 [26] "RemLea"       "RemLeaCl"     "RemLeaSt"     "Politics"     "ConLabDf"    
 [31] "VoteDuty"     "SocTrust"     "EngParl"      "ScotPar2"     "ECPolicy2"   
 [36] "Spend1"       "Spend2"       "SocBen1"      "SOCBEN2"      "DOLE"        
 [41] "TAXSPEND"     "WkMent"       "WkPhys"       "HProbRsp"     "PhsRetn"     
 [46] "PhsRecov"     "MntRetn"      "MntRecov"     "HCWork21"     "HCWork22"    
 [51] "HCWork23"     "HCWork24"     "HCWork25"     "HCWork26"     "HCWork28"    
 [56] "HCWork29"     "HCWork213"    "HCWork214"    "HCWork215"    "HCWork27"    
 [61] "CMtUnmar1"    "CMtUnmar2"    "CMtUnmar3"    "CMtUnmar4"    "CMtUnmar5"   
 [66] "CMtUnmar6"    "CMtUnmar7"    "CMtUnmar8"    "CMtUnmar9"    "CMtUnmar10"  
 [71] "CMtmar1"      "CMtmar2"      "CMtmar3"      "CMtmar4"      "CMtmar5"     
 [76] "CMtmar6"      "CMtmar7"      "CMtmar8"      "CMtmar9"      "CMtmar10"    
 [81] "ChCoSupp"     "ChMIncM"      "ChMIncF"      "ChMCont"      "RBGaran2"    
 [86] "RBGGov"       "DigPCUn"      "DigPCctl"     "DigPCcon"     "DigPCrsk"    
 [91] "DigGVun"      "DigGVctl"     "DigGVcon"     "DigGVrsk"     "DigPro"      
 [96] "NHSSat"       "WkHmNow"      "WkHmJan"      "CovWkc"       "CovNoWkc"    
[101] "CovWkr1"      "CovWkr2"      "CovWkr3"      "CovWkr4"      "CovWkr5"     
[106] "CovWkr6"      "CovWk1"       "CovWk2"       "CovWk3"       "GovtWork"    
[111] "GovTrust"     "CLRTRUST"     "MPsTrust"     "LoseTch"      "VoteIntr"    
[116] "PtyNMat2"     "PolPart01"    "PolPart02"    "PolPart03"    "PolPart04"   
[121] "PolPart05"    "PolPart06"    "PolPart07"    "PolPart08"    "PolPart09"   
[126] "PolPart10"    "PolPart11"    "REFHANG"      "RefSyst"      "UnempJob"    
[131] "SocHelp"      "DoleFidl"     "WelfFeet"     "welfhelp"     "morewelf"    
[136] "damlives"     "proudwlf"     "Redistrb"     "BigBusnN"     "Wealth"      
[141] "RichLaw"      "Indust4"      "TradVals"     "StifSent"     "DeathApp"    
[146] "Obey"         "WrongLaw"     "Censor"       "NatIdGB"      "ChAttend"    
[151] "DisNew2"      "DisAct"       "HEdQual2"     "HhldEdu"      "EURefV2"     
[156] "EUVOTWHO"     "EURefb"       "Voted"        "Vote"         "Anybn3"      
[161] "HHincome"     "Maininc5"     "REarn"        "HIncDif4"     "RetExp"      
[166] "RetExpb"      "FutrWrk"      "PenKnow2"     "PenExp2"      "PenComp"     
[171] "PenIntr"      "INFORET3"     "WkPKnw"       "WKPSav"       "WkPSpn"      
[176] "WPSvUs"       "WPSvWw"       "WPSvEas"      "PrPKnw"       "PrPSav"      
[181] "PrPSpn"       "PrPSvUs"      "PrPSvWW"      "PrPSvEas"     "NCOutcome"   
[186] "Ragecat"      "Ragecat20"    "DisActDV"     "leftrigh"     "libauth"     
[191] "welfare2"     "libauth2"     "leftrig2"     "welfgrp"      "REconAct20"  
[196] "REconSum20"   "RaceOri4"     "LegMarStE"    "HhlAdGpd"     "HhlChlGpd"   
[201] "BestNatU2"    "RetirAg3"     "ReligSum20"   "RlFamSum20"   "EmplStatDV"  
[206] "RClassGP"     "serialh"      "GOR"          "gor2"         "BSA20_wt_new"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Displays the first five</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="do">### lines of a data frame</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(bsa20)  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 210
  serial   QnrVersion RespSx2cat RespAgeE MarStat6 REconFW01 REconFW02 REconFW03
  &lt;dbl+lb&gt; &lt;dbl+lbl&gt;  &lt;dbl+lbl&gt;  &lt;dbl+lb&gt; &lt;dbl+lb&gt; &lt;dbl+lbl&gt; &lt;dbl+lbl&gt; &lt;dbl+lbl&gt;
1 3.21e9   1 [Versio… 2 [Male]   70       5 [Divo… 0 [No]    0 [No]    0 [No]   
2 3.21e9   1 [Versio… 2 [Male]   66       1 [Marr… 0 [No]    0 [No]    0 [No]   
3 3.21e9   1 [Versio… 1 [Female] 64       1 [Marr… 0 [No]    0 [No]    0 [No]   
4 3.21e9   1 [Versio… 2 [Male]   43       1 [Marr… 0 [No]    0 [No]    1 [Yes]  
5 3.21e9   1 [Versio… 1 [Female] 38       1 [Marr… 0 [No]    0 [No]    1 [Yes]  
6 3.21e9   1 [Versio… 2 [Male]   77       1 [Marr… 0 [No]    0 [No]    0 [No]   
# ℹ 202 more variables: REconFW04 &lt;dbl+lbl&gt;, REconFW05 &lt;dbl+lbl&gt;,
#   REconFW06 &lt;dbl+lbl&gt;, REconFW07 &lt;dbl+lbl&gt;, REconFW08 &lt;dbl+lbl&gt;,
#   REconFW09 &lt;dbl+lbl&gt;, REconFW10 &lt;dbl+lbl&gt;, REconFW11 &lt;dbl+lbl&gt;,
#   EMPSTAT &lt;dbl+lbl&gt;, Employ &lt;dbl+lbl&gt;, Superv &lt;dbl+lbl&gt;, EmpOCC &lt;dbl+lbl&gt;,
#   TenureE &lt;dbl+lbl&gt;, SupParty &lt;dbl+lbl&gt;, ClosePty &lt;dbl+lbl&gt;,
#   PARTYFW &lt;dbl+lbl&gt;, Idstrng &lt;dbl+lbl&gt;, RemLea &lt;dbl+lbl&gt;, RemLeaCl &lt;dbl+lbl&gt;,
#   RemLeaSt &lt;dbl+lbl&gt;, Politics &lt;dbl+lbl&gt;, ConLabDf &lt;dbl+lbl&gt;, …</code></pre>
</div>
</div>
<p>The above output is summarised in a <code>haven</code>- imported dataframe format also known as a ‘tibble’. For a really raw output we need to convert into a ‘pure’ data frame. Beware, the output might be very lengthy!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">data.frame</span>(bsa20))  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     serial QnrVersion RespSx2cat RespAgeE MarStat6 REconFW01 REconFW02
1 3.211e+09          1          2       70        5         0         0
2 3.211e+09          1          2       66        1         0         0
3 3.211e+09          1          1       64        1         0         0
4 3.211e+09          1          2       43        1         0         0
5 3.211e+09          1          1       38        1         0         0
6 3.211e+09          1          2       77        1         0         0
  REconFW03 REconFW04 REconFW05 REconFW06 REconFW07 REconFW08 REconFW09
1         0         0         0         0         0         0         1
2         0         0         0         0         0         0         1
3         0         0         0         0         0         0         1
4         1         0         0         0         0         0         0
5         1         0         0         0         0         0         0
6         0         0         0         0         0         0         1
  REconFW10 REconFW11 EMPSTAT Employ Superv EmpOCC TenureE SupParty ClosePty
1         0         0       1      2      1      3      10        1       NA
2         0         0       1      2      1      1       1        1       NA
3         0         0       1      1      2      1       1        1       NA
4         0         0       1      3      1      3       1        2        2
5         0         0       1      3      2      2       1        2        2
6         0         0       3     NA     NA      1       9        1       NA
  PARTYFW Idstrng RemLea RemLeaCl RemLeaSt Politics ConLabDf VoteDuty SocTrust
1       1       2     NA       NA       NA        2       NA       NA        1
2       2       3     NA       NA       NA        3       NA       NA        1
3       2       3     NA       NA       NA        3       NA       NA        1
4       2       3     NA       NA       NA        2       NA       NA        2
5       1       3     NA       NA       NA        3       NA       NA        2
6       1       2     NA       NA       NA        2       NA       NA        2
  EngParl ScotPar2 ECPolicy2 Spend1 Spend2 SocBen1 SOCBEN2 DOLE TAXSPEND WkMent
1      NA       NA        NA      2      1       1       2    1        2      1
2      NA       NA        NA      1      3       2       5    1        2      2
3      NA       NA        NA      3      1       2       3    1        2      2
4      NA       NA        NA      7      3       1       2    2        2      2
5      NA       NA        NA      7      3       2       4    2        2      1
6      NA       NA        NA     98     NA       1       4    2        3      2
  WkPhys HProbRsp PhsRetn PhsRecov MntRetn MntRecov HCWork21 HCWork22 HCWork23
1      1        1       1        2       1        2        1        1        1
2      2        1       1        3       1        2        1        0        1
3      2        1       1        2       1        2        1        1        1
4      2        2       2        3       1        2        1        1        1
5      1        1       1        2       1        2        1        1        1
6      2        2       2        2       2        2        1        0        1
  HCWork24 HCWork25 HCWork26 HCWork28 HCWork29 HCWork213 HCWork214 HCWork215
1        1        1        1        0        0         0         0         0
2        1        1        1        0        0         0         0         0
3        1        1        1        0        0         0         0         0
4        1        1        1        0        0         0         0         0
5        1        1        1        0        0         0         0         0
6        1        1        0        0        0         0         0         0
  HCWork27 CMtUnmar1 CMtUnmar2 CMtUnmar3 CMtUnmar4 CMtUnmar5 CMtUnmar6
1        0         1         2         2         1         1         1
2        0         1         1         1         3         3         1
3        0         1         1         1         3         3         1
4        0        NA        NA        NA        NA        NA        NA
5        0        NA        NA        NA        NA        NA        NA
6        0         1         1         1         3         1         8
  CMtUnmar7 CMtUnmar8 CMtUnmar9 CMtUnmar10 CMtmar1 CMtmar2 CMtmar3 CMtmar4
1         1         2         1          1      NA      NA      NA      NA
2         1         1         3          1      NA      NA      NA      NA
3         1         1         3          3      NA      NA      NA      NA
4        NA        NA        NA         NA       1       1       2       1
5        NA        NA        NA         NA       1       1       1       1
6         1         1         3          1      NA      NA      NA      NA
  CMtmar5 CMtmar6 CMtmar7 CMtmar8 CMtmar9 CMtmar10 ChCoSupp ChMIncM ChMIncF
1      NA      NA      NA      NA      NA       NA        3       1      NA
2      NA      NA      NA      NA      NA       NA        3       2      NA
3      NA      NA      NA      NA      NA       NA        2       2      NA
4       1       1       1       2       1        1       NA      NA       1
5       1       1       1       2       1        1       NA      NA       1
6      NA      NA      NA      NA      NA       NA        3       8      NA
  ChMCont RBGaran2 RBGGov DigPCUn DigPCctl DigPCcon DigPCrsk DigGVun DigGVctl
1       1        2     NA       2        2        2        1      NA       NA
2       4        2     NA       2        3        3        1      NA       NA
3       2        3     NA       3        3        3        8      NA       NA
4      NA       NA     NA      NA       NA       NA       NA       1        2
5      NA       NA     NA      NA       NA       NA       NA       3        3
6       1        1      1       1        3        1        2      NA       NA
  DigGVcon DigGVrsk DigPro NHSSat WkHmNow WkHmJan CovWkc CovNoWkc CovWkr1
1       NA       NA      2      3      NA      NA     NA       NA      NA
2       NA       NA      2      2      NA      NA     NA       NA      NA
3       NA       NA      2      3      NA      NA     NA       NA      NA
4        4        1      2      2       1       2     NA        1       0
5        3        8      1      2       3       3      1       NA       0
6       NA       NA      2      2      NA      NA     NA       NA      NA
  CovWkr2 CovWkr3 CovWkr4 CovWkr5 CovWkr6 CovWk1 CovWk2 CovWk3 GovtWork
1      NA      NA      NA      NA      NA     NA     NA     NA       NA
2      NA      NA      NA      NA      NA     NA     NA     NA       NA
3      NA      NA      NA      NA      NA     NA     NA     NA       NA
4       0       0       0       1       0      5      5      5       NA
5       0       0       0       0       1      3      3      3       NA
6      NA      NA      NA      NA      NA     NA     NA     NA       NA
  GovTrust CLRTRUST MPsTrust LoseTch VoteIntr PtyNMat2 PolPart01 PolPart02
1       NA       NA       NA      NA       NA       NA        NA        NA
2       NA       NA       NA      NA       NA       NA        NA        NA
3       NA       NA       NA      NA       NA       NA        NA        NA
4       NA       NA       NA      NA       NA       NA        NA        NA
5       NA       NA       NA      NA       NA       NA        NA        NA
6       NA       NA       NA      NA       NA       NA        NA        NA
  PolPart03 PolPart04 PolPart05 PolPart06 PolPart07 PolPart08 PolPart09
1        NA        NA        NA        NA        NA        NA        NA
2        NA        NA        NA        NA        NA        NA        NA
3        NA        NA        NA        NA        NA        NA        NA
4        NA        NA        NA        NA        NA        NA        NA
5        NA        NA        NA        NA        NA        NA        NA
6        NA        NA        NA        NA        NA        NA        NA
  PolPart10 PolPart11 REFHANG RefSyst UnempJob SocHelp DoleFidl WelfFeet
1        NA        NA      NA      NA        3       4        4        4
2        NA        NA      NA      NA        3       3        3        4
3        NA        NA      NA      NA        3       4        4        4
4        NA        NA      NA      NA        2       3        3        1
5        NA        NA      NA      NA        2       4        2        3
6        NA        NA      NA      NA        2       2        2        2
  welfhelp morewelf damlives proudwlf Redistrb BigBusnN Wealth RichLaw Indust4
1        4        2        2        1        3        4      3       5       4
2        4        3        1        2        4        3      3       4       4
3        3        3        1        1        3        3      2       3       3
4        2        4        3        3        4        2      2       2       3
5        3        3        3        2        4        2      3       3       4
6        3        3        4        2        4        4      3       5       4
  TradVals StifSent DeathApp Obey WrongLaw Censor NatIdGB ChAttend DisNew2
1        3        3        2    3        4      3       5        7       2
2        4        3        2    2        3      2       6       NA       2
3        3        3        3    2        2      2       1       NA       2
4        2        1        2    1        2      2       3        7       2
5        4        3        3    3        4      2       3       NA       2
6        1        2        3    1        3      2       3        1       2
  DisAct HEdQual2 HhldEdu EURefV2 EUVOTWHO EURefb Voted Vote Anybn3 HHincome
1     NA        2       2      NA       NA     NA     2   NA      1        2
2     NA        1      NA      NA       NA     NA     1    2      2        3
3     NA        2       1      NA       NA     NA     1    2      2        3
4     NA        4       2      NA       NA     NA     1    1      1        4
5     NA        3       2      NA       NA     NA     1    1      1        3
6     NA        1      NA      NA       NA     NA     1    1      1        9
  Maininc5 REarn HIncDif4 RetExp RetExpb FutrWrk PenKnow2 PenExp2 PenComp
1        4    NA        3     NA      NA      NA       NA      NA      NA
2        2    NA        2     NA      NA      NA       NA      NA      NA
3        2    NA        2     NA      NA      NA       NA      NA      NA
4        1     3        2      3      60       2        1    7000       4
5        1     3        3      3      65       1        2     130       2
6        1    NA        3     NA      NA      NA       NA      NA      NA
  PenIntr INFORET3 WkPKnw WKPSav WkPSpn WPSvUs WPSvWw WPSvEas PrPKnw PrPSav
1      NA       NA     NA     NA     NA     NA     NA      NA     NA     NA
2      NA       NA     NA     NA     NA     NA     NA      NA     NA     NA
3      NA       NA     NA     NA     NA     NA     NA      NA     NA     NA
4       2        2      2      1      4      1      1       1     NA     NA
5       2        2      3      1      4      1      2       2     NA     NA
6      NA       NA     NA     NA     NA     NA     NA      NA     NA     NA
  PrPSpn PrPSvUs PrPSvWW PrPSvEas NCOutcome Ragecat Ragecat20 DisActDV leftrigh
1     NA      NA      NA       NA         1       7         6        3      3.8
2     NA      NA      NA       NA         1       7         6        3      3.6
3     NA      NA      NA       NA         1       6         5        3      2.8
4     NA      NA      NA       NA         1       3         3        3      2.6
5     NA      NA      NA       NA         1       3         3        3      3.2
6     NA      NA      NA       NA         1       7         7        3      4.0
   libauth welfare2 libauth2 leftrig2 welfgrp REconAct20 REconSum20 RaceOri4
1 3.000000    2.000        2        3       1          9          6        3
2 3.333333    2.375        2        3       1          9          6        3
3 3.500000    2.125        2        2       1          9          6        3
4 4.333333    3.625        3        2       3          3          2        3
5 2.833333    3.000        2        2       2          3          2        3
6 4.000000    3.500        3        3       2          9          6        3
  LegMarStE HhlAdGpd HhlChlGpd BestNatU2 RetirAg3 ReligSum20 RlFamSum20
1         4        1         0         1       65          3          1
2         1        2         0         3       58          5          2
3         1        2         0         1       54          5          1
4         1        2         1         1       NA          3          2
5         1        2         1         2       NA          5          3
6         1        2         0         2       99          3          3
  EmplStatDV RClassGP   serialh GOR gor2 BSA20_wt_new
1          4        1 321100002   1    1    0.7099859
2          6        1 321100014   1    1    0.3145871
3          7        1 321100014   1    1    0.5649618
4          4        1 321100040   1    1    0.9355446
5          7        2 321100040   1    1    0.6830794
6          3        1 321100042   1    1    1.4006989</code></pre>
</div>
</div>
<p><strong>Questions</strong></p>
<p><em>1. What is the overall sample size?</em></p>
<p><em>2. How many variables are there in the dataset?</em></p>
<p>Now, focus on the three variables we will use.</p>
<p><strong>Note</strong> Traditional statistical software such as SPSS or Stata treat categorical variables as arbitrary numbers. Values labels are then attached, that allocate a substantive meaning to these values. R on the other hand can either directly deal with the value themselves as alphanumeric variables, or with its own version of categorical variables, known as ‘factors’. There aren’t straightforward ways to convert SPSS or Stata labelled categorical variables into R factors.</p>
<p>The <code>haven</code> package that we use here preserves the original numeric values in the data, and add attributes that can be manipulated separately and contain the labels. Attributes are a special type of R objects that have a name, and can be read using the <code>attr()</code> function. Each variable has a ‘label’ and ‘labels’ attribute. The former is the variable description, the latter the value labels.</p>
<p>Alternatively, haven-imported numeric variables can be converted into factors with levels (ie categories) reflecting the SPSS or Stata value labels, but with numeric values different from the original ones.</p>
<p>Let’s examine the original variable description and value labels with the <code>attr()</code> function. We can do this variable by variable…</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attr</span>(bsa20<span class="sc">$</span>TAXSPEND,<span class="st">"label"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "If it had to choose, should govt reduce/increase/maintain levels of taxation and spending?"</code></pre>
</div>
</div>
<p>… Or all at once:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t</span>(                          <span class="co"># Transpose rows and columns for better readability   </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  bsa20 <span class="sc">|&gt;</span> </span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">select</span>(TAXSPEND,EUVOTWHO,PenExp2) <span class="sc">|&gt;</span> <span class="co"># Select the relevant variables</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>        <span class="fu">summarise_all</span>(attr,<span class="st">"label"</span>)  <span class="co"># Apply the attr() function to all of them</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         [,1]                                                                                                 
TAXSPEND "If it had to choose, should govt reduce/increase/maintain levels of taxation and spending?"         
EUVOTWHO "Did you vote to 'remain a member of the EU' or to 'leave the EU'?"                                  
PenExp2  "How much do you think someone who reaches State Pension age today would receive in pounds per week?"</code></pre>
</div>
</div>
<p>We do the same with value labels:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attr</span>(bsa20<span class="sc">$</span>TAXSPEND,<span class="st">"labels"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                        Not applicable 
                                                                    -1 
  Reduce taxes and spend less on health, education and social benefits 
                                                                     1 
    Keep taxes and spending on these services at the same level as now 
                                                                     2 
Increase taxes and spend more on health, education and social benefits 
                                                                     3 
                                                            Don't know 
                                                                     8 
                                                  Prefer not to answer 
                                                                     9 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">attr</span>(bsa20<span class="sc">$</span>EUVOTWHO,<span class="st">"labels"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                       Not applicable Remain a member of the European Union 
                                   -1                                     1 
             Leave the European Union                      I Don't remember 
                                    2                                     3 
                           Don't know                  Prefer not to answer 
                                    8                                     9 </code></pre>
</div>
</div>
<p><strong>Question 3</strong></p>
<p><em>What do the variables measure and how?</em></p>
</section>
<section id="missing-values" class="level3">
<h3 class="anchored" data-anchor-id="missing-values">2. Missing values</h3>
<p>Let’s now examine the distribution of our three variables. We can temporarily convert <code>EUVOTWHO</code> and <code>TAXSPEND</code> into factors using <code>mutate()</code> for a more meaningful output that include their value labels. Review the frequency tables, examining the ‘not applicable’ and ‘don’t know’ categories.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>bsa20<span class="sc">%&gt;%</span><span class="fu">select</span>(EUVOTWHO,TAXSPEND) <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">mutate</span>(<span class="fu">as_factor</span>(.)) <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>       <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                  EUVOTWHO   
 Not applicable                       :   0  
 Remain a member of the European Union: 635  
 Leave the European Union             : 463  
 I Don't remember                     :   2  
 Don't know                           :   0  
 Prefer not to answer                 :  21  
 NA's                                 :2843  
                                                                   TAXSPEND   
 Not applicable                                                        :   0  
 Reduce taxes and spend less on health, education and social benefits  : 186  
 Keep taxes and spending on these services at the same level as now    :1589  
 Increase taxes and spend more on health, education and social benefits:2133  
 Don't know                                                            :  35  
 Prefer not to answer                                                  :  21  
                                                                              </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bsa20<span class="sc">$</span>PenExp2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
      0     120     160    1293     200    9999    1076 </code></pre>
</div>
</div>
<p><strong>Question 4</strong></p>
<p><em>Why are there so many system missing values (NA) for <code>EUVOTWHO</code> and <code>PenExp2</code> ? What does this mean when it comes to interpreting the percentages? You can use the documentation if needed.</em></p>
<p>When analysing survey data, it is sometimes convenient to recode item nonresponses such as ´Don’t know´ and ‘Prefer not to say’ as system missing so that they do not appear in the results. An example of the syntax required to achieve this with EUVOTWHO and TAXSPEND is provided in the appendix.</p>
<p>Unlike some other surveys, ‘Don’t knows’ and ‘Does not apply’ were not removed when weights were computed in the BSA. As a result, analyses using weights (ie when planning to use the data to make inference about the British population) need to retain these observations, otherwise estimated results might be incorrect.</p>
</section>
<section id="compare-unweighted-and-weighted-proportions" class="level3">
<h3 class="anchored" data-anchor-id="compare-unweighted-and-weighted-proportions">3. Compare unweighted and weighted proportions</h3>
<p>In this section, we compare unweighted and weighted prportionso for <code>EUVOTWHO</code> and <code>TAXSPEND</code>. Let’s examine the unweighted responses first. In order to ensure coherence with the remainder of this exercise, we use <code>xtabs()</code> for categorical variables and <code>summary()</code> for continuous ones.</p>
<p>First, as mentioned above, we recode <code>EUVOTWHO</code> and <code>TAXSPEND</code>into factors, with value labels as levels using <code>as_factor()</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>bsa20<span class="ot">&lt;-</span>bsa20<span class="sc">%&gt;%</span><span class="fu">mutate</span>(</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">TAXSPEND.f=</span><span class="fu">as_factor</span>(TAXSPEND,<span class="st">"labels"</span>), </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">EUVOTWHO.f=</span><span class="fu">as_factor</span>(EUVOTWHO,<span class="st">"labels"</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>               )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can truncate factor levels respectively to 14 and 6 characters, for a more human-friendly output using <code>substr()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(bsa20<span class="sc">$</span>TAXSPEND.f)<span class="ot">&lt;-</span><span class="fu">substr</span>(<span class="fu">levels</span>(bsa20<span class="sc">$</span>TAXSPEND.f),<span class="dv">1</span>,<span class="dv">14</span>)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(bsa20<span class="sc">$</span>EUVOTWHO.f)<span class="ot">&lt;-</span><span class="fu">substr</span>(<span class="fu">levels</span>(bsa20<span class="sc">$</span>EUVOTWHO.f),<span class="dv">1</span>,<span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Finally, we compute the proportions:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(                               <span class="do">### Rounds the results to one decimal</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="dv">100</span><span class="sc">*</span>                               <span class="do">### Converts proportions to %  </span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">prop.table</span>(                      <span class="do">### Computes proportions</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">xtabs</span>(<span class="sc">~</span>TAXSPEND.f,bsa20,       <span class="do">### Computes frequencies,</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">drop.unused.levels =</span> T) <span class="do">### Leaves out levels with 0 observations),</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>      ), </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>TAXSPEND.f
Reduce taxes a Keep taxes and Increase taxes     Don't know Prefer not to  
           4.7           40.1           53.8            0.9            0.5 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="dv">100</span><span class="sc">*</span><span class="fu">prop.table</span>(<span class="fu">xtabs</span>(<span class="sc">~</span>EUVOTWHO.f,bsa20,<span class="at">drop.unused.levels =</span> T)),<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>EUVOTWHO.f
Remain Leave  I Don' Prefer 
  56.6   41.3    0.2    1.9 </code></pre>
</div>
</div>
<p>We can also examine the basic summary statistics for <code>PenExp2</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bsa20<span class="sc">$</span>PenExp2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
      0     120     160    1293     200    9999    1076 </code></pre>
</div>
</div>
<p>What is the (unweighted) percentage of respondents who say they voted remain in the EU referendum? About 57 percent of sample members who voted in referendum said they voted to remain. This figure seems a bit high (though people do not always report accurately).</p>
<p>Let’s compare with the weighted frequencies. We will keep using <code>xtabs()</code> for convenience. With <code>xtabs()</code>, weights are specified on the left hand side of the formula as shown below. For the record, <code>wtd.table()</code> function from the <code>Hmisc</code> package also produces weighted frequency tables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(BSA20_wt_new<span class="sc">~</span>EUVOTWHO.f,</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">data=</span>bsa20)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>EUVOTWHO.f
    Not ap     Remain     Leave      I Don'     Don't      Prefer 
  0.000000 565.011079 489.146642   3.752765   0.000000  22.527320 </code></pre>
</div>
</div>
<p>We can get rid of the empty levels to improve the output:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">xtabs</span>(BSA20_wt_new<span class="sc">~</span>EUVOTWHO.f,</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">data=</span>bsa20,</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">drop.unused.levels =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>EUVOTWHO.f
    Remain     Leave      I Don'     Prefer 
565.011079 489.146642   3.752765  22.527320 </code></pre>
</div>
</div>
<p>We convert the weighted frequencies into proportions and examine the results:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>euv.wp<span class="ot">&lt;-</span><span class="fu">round</span>(</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="dv">100</span><span class="sc">*</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">prop.table</span>(</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">xtabs</span>(BSA20_wt_new<span class="sc">~</span>EUVOTWHO.f,</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">data=</span>bsa20,</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">drop.unused.levels =</span> T)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>      ),</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="dv">1</span>)</span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>euv.wp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>EUVOTWHO.f
Remain Leave  I Don' Prefer 
  52.3   45.3    0.3    2.1 </code></pre>
</div>
</div>
<p>Now, what proportion say they voted remain in the EU referendum?</p>
<p>It is about 52 percent, lower than the unweighted proportion and closer to the actual referendum results.</p>
<p>Do you have an idea as to why this might be the case?</p>
<p>A possible explanation is that those more likely to vote ‘Remain’, such as younger people tend to also be less likely to take part in surveys, and therefore their real prevalence in the population will be underestimated by unweighted proportions.</p>
</section>
<section id="confidence-intervals" class="level3">
<h3 class="anchored" data-anchor-id="confidence-intervals">4. Confidence intervals</h3>
<p>So far, we have just computed point estimates without worrying about their precision. Estimates precision (or uncertainty) does matter insofar as it determines how big the ranges within which ‘true’ population values are likely to be. These are also known as the <em>confidence intervals</em> of our estimates.</p>
<p>In this exercise, we will be computing confidence intervals ’by hand‘ and ignore the survey design (ie whether clustering or stratification were used when collecting the sample) as the information is not available in this edition of the BSA. This amounts to assuming that the sample was collected using simple random sampling - which wasn’t the case - and increase the bias of our estimates.</p>
<p>We will explore the more reliable survey design functions provided by the <code>survey</code> package in the next exercise.</p>
<section id="confidence-intervals-for-proportions" class="level4">
<h4 class="anchored" data-anchor-id="confidence-intervals-for-proportions">Confidence intervals for proportions</h4>
<p>The <code>Hmisc</code> package provides <code>binconf()</code> a handy function to compute confidence intervals for proportions. We need to provide it with two parameters: the frequencies for which we would like a confidence interval, and the total number of non missing observations. <code>binconf()</code> accepts individual proportions or complete frequency tables as input.</p>
<p>We begin with the unweighted confidence interval for EUVOTWHO:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>eu.ci<span class="ot">&lt;-</span><span class="fu">binconf</span>(<span class="fu">xtabs</span>(<span class="sc">~</span>EUVOTWHO.f,</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>                     bsa20,</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">drop.unused.levels =</span> T)[<span class="dv">1</span>],</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>               <span class="fu">sum</span>(<span class="fu">xtabs</span>(<span class="sc">~</span>EUVOTWHO.f,bsa20)))</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>eu.ci</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  PointEst     Lower     Upper
 0.5664585 0.5372704 0.5951927</code></pre>
</div>
</div>
<p>We convert the output into rounded percentages for better readability:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="dv">100</span><span class="sc">*</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>      eu.ci,</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>      <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> PointEst Lower Upper
     56.6  53.7  59.5</code></pre>
</div>
</div>
<p>We can adapt the syntax above to make it work with weighted frequencies:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="dv">100</span><span class="sc">*</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">binconf</span>(<span class="fu">xtabs</span>(bsa20<span class="sc">$</span>BSA20_wt_new<span class="sc">~</span>EUVOTWHO.f,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">data=</span>bsa20,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">drop.unused.levels =</span> T)[<span class="dv">2</span>],</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>          <span class="fu">sum</span>(<span class="fu">xtabs</span>(bsa20<span class="sc">$</span>BSA20_wt_new<span class="sc">~</span>EUVOTWHO.f,</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data=</span>bsa20,</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">drop.unused.levels =</span> T))),</span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>      <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> PointEst Lower Upper
     45.3  42.3  48.3</code></pre>
</div>
</div>
<p>What are the differences between weighted and unweighted confidence intervals for the proportion of people who voted remain?</p>
<p>Let us now do the same with people’s views about government tax and spending.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>ciprop<span class="ot">&lt;-</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="dv">100</span><span class="sc">*</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">binconf</span>(<span class="fu">xtabs</span>(BSA20_wt_new<span class="sc">~</span>TAXSPEND.f,</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">data=</span>bsa20,</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">drop.unused.levels=</span>T),</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>        <span class="fu">sum</span>(<span class="fu">xtabs</span>(BSA20_wt_new<span class="sc">~</span>TAXSPEND.f,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>                  bsa20))),</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span>)</span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>ciprop</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> PointEst Lower Upper
      5.5   4.8   6.3
     42.8  41.3  44.3
     50.3  48.8  51.9
      0.9   0.6   1.2
      0.5   0.3   0.8</code></pre>
</div>
</div>
<p>We can improve the layout by adding the value labels. In order to do this, we create a data frame with the results of the above computation <code>ciprop</code> and specify that the row names should be the original value labels of TAXSPEND using as_factor. We also however need to omit the first label ‘Not applicable’ as we removed it earlier.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>ciprop.l<span class="ot">&lt;-</span><span class="fu">data.frame</span>(</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>           ciprop,</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">row.names=</span><span class="fu">levels</span>(</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>                     bsa20<span class="sc">$</span>TAXSPEND.f</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>                     )[<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>           )</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>ciprop.l</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               PointEst Lower Upper
Reduce taxes a      5.5   4.8   6.3
Keep taxes and     42.8  41.3  44.3
Increase taxes     50.3  48.8  51.9
Don't know          0.9   0.6   1.2
Prefer not to       0.5   0.3   0.8</code></pre>
</div>
</div>
<p><strong>Question 5.</strong></p>
<p><em>What proportion think government should increase taxes and spend more on health, education and social benefits?</em></p>
</section>
<section id="confidence-intervals-for-means" class="level4">
<h4 class="anchored" data-anchor-id="confidence-intervals-for-means">Confidence intervals for means</h4>
<p>Several R packages offer functions for computing confidence intervals and standard errors of means. Here, we privilege doing things by hand in order to properly understand what is happening in the background.</p>
<p>Under assumptions of simple random sampling, a 95% confidence interval of the mean is defined as plus or minus 1.96 times its standard error. The standard error of the mean is its standard deviation – that is, the square root of its variance – divided by the square root of the sample size.</p>
<p>We will be using <code>wtd.mean</code> from the <code>Hmisc</code> package to compute weighted means, and <code>wtd.var</code> for variances. We can therefore compute:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>m.p<span class="ot">&lt;-</span><span class="fu">wtd.mean</span>(bsa20<span class="sc">$</span>PenExp2,<span class="at">weights=</span>bsa20<span class="sc">$</span>BSA20_wt_new)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>se.p<span class="ot">&lt;-</span><span class="fu">sqrt</span>(<span class="fu">wtd.var</span>(bsa20<span class="sc">$</span>PenExp2,<span class="at">weights=</span>bsa20<span class="sc">$</span>BSA20_wt_new))</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="fu">sum</span>(bsa20<span class="sc">$</span>BSA20_wt_new[<span class="sc">!</span><span class="fu">is.na</span>(bsa20<span class="sc">$</span>PenExp2)])</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>ci<span class="ot">&lt;-</span><span class="fu">c</span>(m.p,m.p<span class="fl">-1.96</span><span class="sc">*</span>(se.p<span class="sc">/</span><span class="fu">sqrt</span>(n)),m.p<span class="fl">+1.96</span><span class="sc">*</span>(se.p<span class="sc">/</span><span class="fu">sqrt</span>(n)))</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(ci,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1305.9 1194.4 1417.5</code></pre>
</div>
</div>
<p><strong>Question 6</strong></p>
<p><em>How much do people think they will get at state pension age?</em></p>
</section>
</section>
<section id="answers" class="level3">
<h3 class="anchored" data-anchor-id="answers">Answers</h3>
<ol type="1">
<li><p>There are 3964 cases in the dataset.</p></li>
<li><p>The total number of variables is 212.</p></li>
<li><p><em><code>TAXSPEND</code> records responses to the questions of whether government should reduce/increase/maintain levels of taxation and spending. There are three possible responses to the question.</em> <code>EUVOTWHO</code> records responses to the question ‘Did you vote to ’remain a member of the EU’ or to ‘leave the EU’?’ The responses are ‘Remain’ or ‘Leave’. *<code>PenExp2</code> contains responses to the question ‘How much do you think someone who reaches State Pension age today would receive in pounds per week?’ Responses are numeric.</p></li>
<li><p>There are two reasons for the many ‘Not applicable’.</p></li>
</ol>
<ul>
<li>Routing: the question is only asked to those who said yes to a previous question (EURefV2).</li>
<li>Versions 5 and 6 - The BSA uses a split sample and the question is only asked in Versions 5 and 6.</li>
</ul>
<ol start="5" type="1">
<li><p>Between 48.8 and 51.9% in the population say the government should increase taxes and spend more.</p></li>
<li><p>The amount people think they will get at state pension age varies between £1194 and £1417, with an average (ie mean) in the region of £1306.</p></li>
</ol>
</section>
<section id="appendix-recoding-nonresponses-as-system-missing-na" class="level2">
<h2 class="anchored" data-anchor-id="appendix-recoding-nonresponses-as-system-missing-na">Appendix: recoding nonresponses as system missing (NA)</h2>
<p>The code below provides and example of how to recode missing values into system missing (NA) using separate variables. For ease of interpretation, we also convert the original numeric variable into labelled factors using <code>as_factor()</code>, so that they directly display the value labels.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>bsa20<span class="ot">&lt;-</span>bsa20<span class="sc">%&gt;%</span><span class="fu">mutate</span>(</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">TAXSPEND.r=</span><span class="fu">factor</span>(<span class="fu">as_factor</span>(TAXSPEND,<span class="st">"labels"</span>), </span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>                                <span class="at">exclude =</span> <span class="fu">c</span>(<span class="st">"Prefer not to answer"</span>,</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>                                            <span class="st">"Don't know"</span>)),</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">EUVOTWHO.r=</span><span class="fu">factor</span>(<span class="fu">as_factor</span>(EUVOTWHO,<span class="st">"labels"</span>),</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>                                <span class="at">exclude =</span> <span class="fu">c</span>(<span class="st">"Prefer not to answer"</span>,</span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>                                            <span class="st">"I Don't remember"</span>,</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>                                            <span class="st">"Not applicable"</span>,<span class="cn">NA</span>)),</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">PenExp2.r=</span><span class="fu">ifelse</span>(PenExp2<span class="sc">==-</span><span class="dv">1</span> <span class="sc">|</span> PenExp2<span class="sc">&gt;=</span><span class="dv">9998</span>,<span class="cn">NA</span>,PenExp2)</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>                      )</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a><span class="do">### Value labels need to be truncated as they are rather lengthy!</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(bsa20<span class="sc">$</span>TAXSPEND.r)<span class="ot">&lt;-</span><span class="fu">substr</span>(<span class="fu">levels</span>(bsa20<span class="sc">$</span>TAXSPEND.r),<span class="dv">1</span>,<span class="dv">14</span>)</span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(bsa20<span class="sc">$</span>EUVOTWHO.r)<span class="ot">&lt;-</span><span class="fu">substr</span>(<span class="fu">levels</span>(bsa20<span class="sc">$</span>EUVOTWHO.r),<span class="dv">1</span>,<span class="dv">6</span>)</span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(bsa20<span class="sc">$</span>TAXSPEND.r)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Reduce taxes a" "Keep taxes and" "Increase taxes"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(bsa20<span class="sc">$</span>EUVOTWHO.r)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Remain" "Leave "</code></pre>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




<script src="Population estimates using the BSAS with R_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>